apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coco-beach
  namespace: argocd
  labels:
    env: dev
spec:
  project: default

  source:
    repoURL: https://github.com/bnelli123/argocd.git
    targetRevision: HEAD
    path: charts/blue-beach
    helm:
      releaseName: coco-release
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
